version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/apps/linode-marketplace-*"
    schedule:
      interval: "daily"
      time: "13:00"
    groups:
      major-version:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "major"
      minor-version:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 1
    target-branch: "develop"

