---
- name: install phpmyadmin and dependencies
  apt:
    pkg: 
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
      - php-mbstring
      - php-zip
      - php-gd
      - php-json
      - php-curl
      - php-cli
      - phpmyadmin
    state: present

- name: enable mbstring
  command: phpenmod mbstring
  register: mbstring_result
  changed_when: mbstring_result.rc == 0

- name: restart apache
  service:
    name: apache2
    state: restarted



