---
  - name: copy MOTD template to /etc/motd
    template:
      src: templates/motd.j2
      dest: /etc/motd

  - name: writing creds into file
    copy:
      dest: /root/.credentials
      mode: '0600'
      content: |
        Sudo Username: {{ username }}
        Sudo Password: {{ password }}
        Odoo Database name: odoo
        Postgres Password: {{ postgres_password }}