---
# mysql
- name: installing mariadb
  apt:
    pkg:
    - mariadb-server
    - python3-mysqldb
    state: present
  register: mariadb

- name: running mysql secure installation
  import_role:
    name: securemysql
  notify: restart mariadb

- name: copy motd template
  ansible.builtin.template: 
    src: templates/motd.j2
    dest: /etc/motd