---
# set app specific ufw rules 
- name: Allow all access to tcp port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow all access to vnc ports
  community.general.ufw:
    rule: allow
    port: '61000'
    proto: tcp

- name: Allow all access to vnc ports
  community.general.ufw:
    rule: allow
    port: '5901'
    proto: tcp