
# vnc setup
# run as import from kali
# or use provision.yml and deploy.sh to 
# write vars ala wordpress
- name: Install vnc
  apt:
    name:
    - xfce4
    - xfce4-goodies
    - dbus-x11
    - tigervnc-standalone-server
    state: present

- name: create vnc vnc_user
  ansible.builtin.user:
    name: '{{ vnc_username }}'
    create_home: true
    state: present

- name: Create .vnc dirs
  ansible.builtin.file:
    path: /home/'{{ vnc_username }}'/.vnc
    state: directory
    mode: "0755"
    owner: '{{ vnc_username }}'
    group: '{{ vnc_username }}'

- name: touch vnc password
  ansible.builtin.file:
    path: /home/'{{ vnc_username }}'/.vnc/passwd
    mode: "0700"
    owner: '{{ vnc_username }}'
    group: '{{ vnc_username }}'
    state: touch

- name: set vnc password
  ansible.builtin.lineinfile:
    path: /home/'{{ vnc_username }}'/.vnc/passwd
    line: '{{ vnc_password }}'

- name: template vnc service file
  ansible.builtin.template:
    src: templates/vncserver.service.j2
    dest: /etc/systemd/system/vncserver.service
  notify:
    - daemon reload
    - restart vnc
