---
- name: run docker helper
  import_role:
    name: docker

- name: install docker-compose
  apt:
    pkg:
      - docker-compose-plugin
    state: present

- name: run docker
  systemd_service:
    name: docker
    state: started
    enabled: true
