---
- name: copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd

- name: writing owncloud creds into file
  copy:
    dest: /home/{{ username }}/.credentials
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: '0600'
    content: |
      Sudo Username: {{ username }}
      Sudo Password: {{ password }}
      Owncloud Infinite Scale Admin User: {{ ocis_admin }}
      Owncloud Infinite Scale Admin Password: {{ ocis_admin_password }}
